Creates the dev branch out of changes in master.

diff --git a/android-sync b/android-sync
--- a/android-sync
+++ b/android-sync
@@ -2,31 +2,63 @@
 
 set -e
 
+echo "Running Main App"
+
+
 # R-syncs files inside an android phone with existing direcroy.
 # It takes one argument, the path to sync. This command is supposed to be run from within the sync directory
 
 # @TODO accept 2nd argument for the destination
 
-dir_src=/run/user/$UID/gvfs/mtp*
-dir_dest=$(pwd)
 
-path_to_sync=$1
+main() {
+  cmd=$(build_command ${@})
+  run $cmd
+}
 
-# Default to "."
-path_to_sync=${path_to_sync:-.}
+get_src_dir() {
+  echo /run/user/$UID/gvfs/mtp*
+}
 
-# Remove trailing slash
-path_to_sync=${path_to_sync%/}
+build_command() {
+  local path_to_sync="$1"
+  echo $path_to_sync
+  echo "WORK IN PROGRESS"
+  echo "Start here: https://stackoverflow.com/questions/5819423/bash-variables-with-spaces"
+  echo "We are trying to read cd /_extra/android_sync/data && android-sync 'Card/Voice Recorder'"
+  exit 2
 
-cmd="rsync -av $dir_src/$path_to_sync/ $path_to_sync -n"
+  # Default to "."
+  path_to_sync=${path_to_sync:-.}
+  # Remove trailing slash
+  path_to_sync=${path_to_sync%/}
+  dir_src=$(get_src_dir)
+  cmd="rsync -av $dir_src/$path_to_sync/ $path_to_sync"
+  echo $cmd
+}
 
-cd $dir_src
-[ ! -d "Phone" ] && echo "[ERROR] Phone not mounted. Exiting now." && exit
+run() {
 
-echo "[CMD] $cmd"
-read -p 'Run? y/n ' run
+  local __cmd=${@}
 
-[ $run != "y" ] && echo "Cancled." && exit
+  dir_src=$(get_src_dir)
+  cd $dir_src
 
-$cmd
+  [ ! -d "Phone" ] && echo "[ERROR] Phone not mounted. Exiting now." && exit
+
+  echo "[CMD] $__cmd"
+  read -p 'yes or --dry-run? y/D' dry_run
+
+  case "$dry_run" in
+    "y")
+      $__cmd
+      ;;
+    "*")
+      echo "'--dry-running'-ing"
+      $__cmd --dry-run
+      ;;
+  esac
+}
+
+[ -z "$IS_TESTING" ] && main ${@}
 
